<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
$attributeSetRepository = $attributeSet->get($product->getAttributeSetId());
$attribute_set_name = $attributeSetRepository->getAttributeSetName();
$mediaclipprojectid = 0;

if ($_item->getMediaclipProjectId()) {
    $mediaclipprojectid = $_item->getMediaclipProjectId();
}

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" class="col item">
            <?php if ($block->hasProductUrl()):?>
                 
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($mediaclipprojectid) ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   target="_blank"
                   class="product-item-photo">
                   
            <?php else:?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php if($product->getAttributeSetId() != 4 ): ?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($mediaclipprojectid) ?>">
                    
                    <img class="hub-project-thumbnail" data-hub-project-id="<?php echo $mediaclipprojectid ?>" src="" />
                </a>
            <?php else: ?>
            <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
            <?php endif; ?>
            <?php if ($block->hasProductUrl()):?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()):?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($mediaclipprojectid) ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?php echo $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()):?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) : ?>
                            <?php if($_option['label'] != 'Project'): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <?php if($product->getAttributeSetId() != 4 && $product->getMediaclipDustjacketPopup()): ?>
                            <dt>
                                <a href="javascript:void(0)" class="newClass" data ="<?php echo $product->getMediaclipDustjacketPopup(); ?>" style="color:#81c89d; font-weight: bold;"><?php echo $this->escapeHtml('Add dust jacket') ?></a>
                            </dt>
                        <?php endif; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div><?php echo $block->escapeHtml($message['text']) ?></div></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>
        <td class="col-edit a-center">
        <?php if ($isVisibleProduct): ?>
        <a href="<?php echo $this->getProductUrl($mediaclipprojectid); ?>" title="<?php echo __('Edit item parameters') ?>"><?php echo __('Edit') ?></a>
        <?php endif ?>
    </td>
        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
                        <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
                <?php echo $block->getUnitPriceHtml($_item); ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <?php  $disabled = '' ; ?>
        <?php if($product->getAttributeSetId() != 4 && ($attribute_set_name == 'Print')): ?>
            <?php $disabled = "disabled"; ?>
        <?php endif; ?>
            <div class="field qty">
                <label class="label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                           name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                           data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                           value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                           class="input-text qty"
                           maxlength="12"
                           <?php echo $disabled ?>
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal'));?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?php echo $block->getRowTotalHtml($_item); ?>
            <?php endif; ?>
        </td>

    </tr>
    <tr class="item-actions">
        <td colspan="100">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
<script type="text/javascript">
    require([
    'jquery',
    'Magento_Ui/js/modal/modal'
    ],  function ($, modal){

        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            /*title: 'Title',*/
            buttons: [{
                text: $.mage.__('Proceed'),
                class: '',
                click: function () {
                /* some stuff */
                    this.closeModal();
                }
            }]
        };
        $('body').on('click','.newClass',function(e){
            e.preventDefault();
            promptElementId = $(this).attr('data');
            var popup = modal(options,$('#'+promptElementId));            
            $('#'+promptElementId).modal('openModal');
        });
        $(document).on('click','.closeModal',function(e){
            e.preventDefault();
            var popup = modal(options,$('#'+promptElementId));            
            $('#'+promptElementId).modal('closeModal');
        });
    });
</script>