<div class="">
    <div class="entry-edit-head">
        <h4><?php echo __('Mediaclip Order Status'); ?></h4>
    </div>
</div>
<div id="mediaclip_order_status_container" class="box">
<!-- 2019-02-26 Dmitry Fedyuk https://www.upwork.com/fl/mage2pro
1) It was the following commented out code block here:
https://github.com/Inkifi-Connect/Media-Clip-Inkifi/blob/04a97afdcd87bbe710717c45acd54a3e8ab9bb1a/view/adminhtml/templates/order/download.phtml#L8-L95
2) "It looks like the «Mediaclip Order Status» tab on a backend order page is always empty
because it is wrongly programmed": https://github.com/Inkifi-Connect/Media-Clip-Inkifi/issues/2
-->