<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="row">
<div class="col-md-12">
<div class="block block-customer-login" id="account-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getBaseUrl().'mediacliphub/customer/login/' ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <ul class="messages" style="display: none;"><li class="msg" style=""><ul><li><span></span></li></ul></li></ul>
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
</div>
</div>

<script>
require([
    'jquery'
], function($){

     if(jQuery(".fancybox-opened").hasClass("close-popup")){
        jQuery(this).removeClass("close-popup");
     }
    //var loginForm = new VarienForm('login-form', true);
    //var registerForm = new VarienForm('register-form', true);

    //jQuery('.block-content').on('submit', 'form#login-form' ,function(e){
    jQuery('#login-form').submit(function(e){
        
        e.preventDefault();
        var ele = jQuery('#account-login .messages');
        jQuery(ele).hide();
        //jQuery('.block-new-customer').hide();
        //jQuery('.block-customer-login').hide();
        //if (loginForm.validator.validate()) {
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $block->getBaseUrl().'mediacliphub/customer/login/'; ?>",
                dataType: "json",
                data: jQuery('#login-form').serialize(true),
                success: function (response) {
                    
                    if (response.success === true) {
                        console.log('token - '+response.token);
                        console.log('oldToken - '+response.oldToken);
                        javascript:parent.setMediaclipUserToken(response.token);
                        jQuery(ele).find('.msg').removeClass('error-msg');
                        jQuery(ele).find('.msg').addClass('success-msg');
                        jQuery(ele).find('span').html(response.data);
                        jQuery(ele).show();
                        javascript:parent.jQuery.fancybox.close();
                        javascript:parent.jQuery('#product_addtocart_form').submit();

                    } else if (response.error === true) {
                        console.log('token123321 - '+response.token);
                        jQuery(ele).find('.msg').removeClass('success-msg');
                        jQuery(ele).find('.msg').addClass('error-msg');
                        jQuery(ele).find('span').html(response.data);
                        jQuery(ele).show();
                    }


                    jQuery(".fancybox-opened").append("<a href='javascirp:void(0)'>Close</a>");
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    jQuery(ele).find('.msg').removeClass('success-msg');
                    jQuery(ele).find('.msg').addClass('error-msg');
                    jQuery(ele).find('span').html('There is some error while processing you request please try again.');
                    jQuery(ele).show();
                }
            });
        //}
    });
    jQuery('.custom_customer_account').submit(function(e){
        
        e.preventDefault();
        var ele = jQuery('#account-create .messages');
        jQuery(ele).hide();
        //if (registerForm.validator.validate()) {
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $block->getBaseUrl()."mediacliphub/customer/create/"; ?>",
                dataType: "json",
                data: jQuery('.custom_customer_account').serialize(true),
                success: function (response) {
                    console.log('response=>');
                    console.log(response);
                    if (response.success === true) {
                        javascript:parent.setMediaclipUserToken(response.token);
                        jQuery(ele).find('.msg').removeClass('error-msg');
                        jQuery(ele).find('.msg').addClass('success-msg');
                        jQuery(ele).find('span').html(response.data);
                        jQuery(ele).show();
                        javascript:parent.jQuery.fancybox.close();
                        javascript:parent.jQuery('#product_addtocart_form').submit();
                    } else if (response.error === true) {
                        jQuery(ele).find('.msg').removeClass('success-msg');
                        jQuery(ele).find('.msg').addClass('error-msg');
                        jQuery(ele).find('span').html(response.data);
                        jQuery(ele).show();
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    jQuery(ele).find('.msg').removeClass('success-msg');
                    jQuery(ele).find('.msg').addClass('error-msg');
                    jQuery(ele).find('span').html('There is some error while processing you request please try again.');
                    jQuery(ele).show();
                }
            });
        //}
    });
});
</script>